name: Laravel

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: composer install
        working-directory: WebAndApiExt

      # Only build artifacts on push events
      - name: Build package
        if: github.event_name == 'push'
        run: php artisan package:discover && composer build
        working-directory: WebAndApiExt

      # Publish artifacts on release events
      - name: Publish package
        if: github.event_name == 'release' || github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.release.tag_name }}
          release_name: "New Release"
          body: ${{ github.event.release.body }}
          draft: false
          prerelease: false
          files: |
            WebAndApiExt/vendor
            WebAndApiExt/config
            WebAndApiExt/database
            WebAndApiExt/public
          token: ${{ secrets.PAT }} 
          
  # Separate job for running tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: composer install
        working-directory: WebAndApiExt

      # Only run tests on pull requests or merge to main
      - name: Run tests
        if: github.event.pull_request || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: composer test
        working-directory: WebAndApiExt
